@BreweryFinder.API_HostAddress = https://localhost:7178

GET {{BreweryFinder.API_HostAddress}}/GetBreweries/byCity?flint
Accept: application/json

###
# https://www.openbrewerydb.org/documentation/
GET https://api.openbrewerydb.org/v1/breweries?by_state=michigan&per_page=3&by_type=micro